### ISSUE TITLE
Better UI for autocomplete

### ISSUE THREAD

**Issue by misostc** [MeoMix/SongBuzz#21]
This jQuery UI theme might work better for your project. Check it out! [Aristo](http://taitems.tumblr.com/post/482577430/introducing-aristo-a-jquery-ui-theme)

**Comment by MeoMix** [comment]
I checked it out and it does look nicer! The font takes up a bit less space while being more easily read. Not sure how I feel about the blue highlight on select. I changed to the Aristo theme, but left smoothness in just to play around with them both again in the future. Thanks!
