### ISSUE TITLE
Introduce an 'Options' menu instead of the current song-specific icons

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/SongBuzz#33]
So, instead of having 'X' and '+' I think there should just be one icon that expands a context-menu-esque tooltip when hovered. This will allow the user to select options such as Copy Song URL, Copy Song URL + Name, Delete Song, Share Song, etc...

Seems easier to grow in that way than just stacking on icons.

**Comment by misostc** [comment]
Why not have it just in the context menu? You could make some custom right click menu, here: http://jsfiddle.net/s6rpc/

**Comment by MeoMix** [comment]
:D Man. You're a creative genius. I leveraged your idea and am happy with the results. Just committed it in. Probably still a bit buggy for now, but it seems to be working + cleaned up my code!

**Comment by misostc** [comment]
You should add some code that would reposition the menu if it would be shown near the edge of the screen. If you wanted to delete for example the last song, it would be impossible in a long list.

**Comment by MeoMix** [comment]
Fixed!
