### ISSUE TITLE
Songs banned on copyright grounds generate 403 errors

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/SongBuzz#34]
Try adding this song: http://www.youtube.com/watch?v=QXtPoNfOYSo

It was just recently banned. If I try and request the data for it I get:

GET http://gdata.youtube.com/feeds/api/videos/QXtPoNfOYSo?v=2&alt=json-in-script&callback=jQuery172030717645050026476_1343705430535&_=1343705435664 403 (Forbidden) 

Even if I use an ajax request and handle the error event. I need to respond appropriately in this scenario.... which is tricky because I don't get any information about the song.

Not sure how to fix this other than just saying "Oops, can't handle."

**Comment by sabarasaba** [comment]
Its just like you said, since we dont have any sort of way to get the information of the video, showing a dialogbox saying the video is banned for copyright issues is the only thing we can do in this scenario.

**Comment by MeoMix** [comment]
I think that we will be OK on this. I don't think users try and explicitly add very many songs that are banned on copyright grounds. Will need to reconsider when mass-imports are available because then it is more likely they will try and explicitly add multiple banned songs.

I think the other thing to be concerned about is having a song be banned that is already in the playlist. Luckily, we have all the info at that point -- so it is possible to go find a new, unbanned version.

**Comment by MeoMix** [comment]
Hey!

I've reopened this :) Take a look at http://www.youtube-mp3.org/ and give it the URLhttp://www.youtube.com/watch?v=QXtPoNfOYSo

Even though the song is banned on copyright grounds -- they have managed to bypass this and allow for a download of the song. More crazily, they were able to get full song information from a URL of a copyright banned song. Clearly there is a way to do it.

**Comment by MeoMix** [comment]
Unless they've managed to cache the video's information before it was banned... hmm
