### ISSUE TITLE
Need to make it easier to add URLs on the fly.

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/SongBuzz#35]
Not sure how this will be accomplished just yet, but I wanted to write down the thought.

Currently I don't like using my own app because it is easier to go "alt+D, youtube: <song name>" and pull up a song via URL.

I am wondering how feasible this will be in SongBuzz. I think 'very feasible.' Going to play with experimental keybindings -- maybe a keybinding can open up a desktop notification that has the URL input in it?

**Comment by misostc** [comment]
Mabye you could check the user's clipboard if he copied a YouTube URL and then automatically add that URL to the input field when the user opens the player.

**Comment by MeoMix** [comment]
So here's what I've done so far. Not sure if it needs more:

Ctrl+Z keybind will now open the extension (Requires Google Chrome Beta (v22))
On open -- Add Songs input expands and focuses. User can just type at this point -- should be just as fast as using Google Chrome's URL bar.

I might also implement adding URLs from the clipboard or from open tabs, but need to check the currently loaded playlist to make sure the song doesn't exist already. No matter what I think the 'feel' would never be quite right for adding songs automatically like that, though, but who knows.
