### ISSUE TITLE
Better animation for the title of the song

### ISSUE THREAD

**Issue by misostc** [MeoMix/SongBuzz#38]
The animation for the title is a bit weird. I would suggest "linear" animation in jQuery. So in [this line](https://github.com/MeoMix/SongBuzz/blob/master/js/foreground/header.js#L14) of code I would add "linear" to the animation function. The animation will then not slow down in the end.

**Comment by MeoMix** [comment]
Fixed! Thanks... I had noticed this earlier, but it kept slipping my mind. Thanks for making the bug report.
