### ISSUE TITLE
Add mousewheel events on sliders

### ISSUE THREAD

**Issue by misostc** [MeoMix/SongBuzz#39]
It would be easier to control the sliders with your mousewheel instead of clicking and dragging.

**Comment by MeoMix** [comment]
I've implemented this for the volume slider. Controlling the song's progress bar is trickier and I'm not sure if it's entirely warranted. The functionality doesn't exist on YouTube -- but I admit it could be nice to scroll back to the start of a song.

**Comment by MeoMix** [comment]
Okay I stopped being lazy and added the code for the progress bar, too.
